### ISSUE TITLE
Support for graphql => 1.0.0

### ISSUE THREAD

**Issue by marcgreenstock** [nettofarah/graphql-query-resolver#1]
I would love to try your gem but its runtime dependency on `graphql` is pessimistically restricted at `~> 1.0.0`.

Any chance it can be a little more optimistic?

https://github.com/nettofarah/graphql-query-resolver/blob/master/graphql-query-resolver.gemspec#L22

**Comment by nettofarah** [comment]
Hey, @marcgreenstock.
For sure! Let's change it.

What version of graphql-ruby are you using at the moment?

**Comment by marcgreenstock** [comment]
hey @nettofarah, i'm using 1.5.5

**Comment by nettofarah** [comment]
Now that I think of it, we don't even need to have a dependency on `graphql-ruby` since everything can be resolved at runtime.

**Comment by nettofarah** [comment]
Done! Just released 0.1.2 with `graphql >= 1.0.0`
Thanks for catching this, @marcgreenstock

**Comment by marcgreenstock** [comment]
awesome, I'll give it a try
